Various cron script improvements.
- Improve wording.
- Pipe STDOUT to /dev/null should not be necessary after using MAILTO="".
- Adapt shebang.

Signed-off-by: Volker Theile <votdev@gmx.de>

diff --git a/deb/openmediavault/etc/cron.daily/openmediavault-check_btrfs_errors b/deb/openmediavault/etc/cron.daily/openmediavault-check_btrfs_errors
--- a/deb/openmediavault/etc/cron.daily/openmediavault-check_btrfs_errors
+++ b/deb/openmediavault/etc/cron.daily/openmediavault-check_btrfs_errors
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env sh
 #
 # This file is part of OpenMediaVault.
 #
@@ -30,22 +30,25 @@ OMV_BTRFS_ERROR_CHECK_ENABLED=${OMV_BTRFS_ERROR_CHECK_ENABLED:-"yes"}
 # Exit immediately if Btrfs error checking is disabled.
 ! omv_checkyesno "${OMV_BTRFS_ERROR_CHECK_ENABLED}" && exit 0
 
-omv_syslog_info "Performing an error check on Btrfs file systems."
+omv_info "Performing an error check on Btrfs file systems."
 findmnt --all --canonicalize --notruncate --uniq --noheadings --output SOURCE,TARGET --types btrfs |
-    sort |
-    while read row
+  sort |
+  while read row
 do
-     device=${row% *}
-     mountpoint=${row#* }
-     omv_syslog_info "Checking ${device} for errors ..."
-     stats=$(btrfs device stats --check "${mountpoint}")
-     if [ $? -ne 0 ]; then
-         omv_syslog_warning "Errors were detected on the file system ${device}."
-         # Ignore the file system notification settings because of the
-         # importance of this message.
-         (
-             echo -e "Errors were detected on the Btrfs file system that is mounted under ${mountpoint}.\n";
-             echo "${stats}"
-         ) | mail -E -s "Errors were detected on the file system ${device}" root
-     fi
+  device=${row% *}
+  mountpoint=${row#* }
+
+  omv_info "Checking ${device} for errors ..."
+
+  stats=$(btrfs device stats --check "${mountpoint}")
+  if [ $? -ne 0 ]; then
+    omv_warning "Errors were detected on the file system ${device}."
+    # Ignore the file system notification settings because of the
+    # importance of this message.
+    (
+      echo "Errors were detected on the Btrfs file system that is mounted at ${mountpoint}.";
+      echo ""
+      echo "${stats}"
+    ) | mail -E -s "Errors were detected on the file system ${device}" root
+  fi
 done
