Update shairport-sync to 2.4.1.

diff --git a/deb/shairport-sync/debian/shairport-sync.init b/deb/shairport-sync/debian/shairport-sync.init
--- a/deb/shairport-sync/debian/shairport-sync.init
+++ b/deb/shairport-sync/debian/shairport-sync.init
@@ -1,42 +1,37 @@
 #! /bin/sh
 ### BEGIN INIT INFO
 # Provides:          shairport-sync
-# Required-Start:    $remote_fs $networking
-# Required-Stop:     $remote_fs $networking
-# Should-Start:      pulseaudio alsa-utils hostname avahi
-# Should-Stop:       pulseaudio alsa-utils hostname avahi
+# Required-Start:    $all
+# Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Shairport Synchronous AirPlay
 # Description:       Implements a synchronous (multi-room-capable) AirPlay receiver
 ### END INIT INFO
 
-# Do not modify this file. Edit /etc/default/shairport-sync instead !
+# Author: Mike Brady <mikebrady@eircom.net>
+#
+# Do NOT "set -e"
 
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="AirPlay Synchronous Audio Service"
 NAME=shairport-sync
 DAEMON=/usr/bin/$NAME
 
-# Configuration defaults
+# We don't use the DAEMON_ARGS variable here because some of the identifiers may have spaces in them, and so are
+# impossible to pass as arguments.
+
+# Instead, we add the arguments directly to the relevant line in the do_start() function below
+
 PIDFILE=/var/run/$NAME.pid
-AP_NAME=$(hostname)
-NICE=0
-
-test -f /etc/default/$NAME && . /etc/default/$NAME
-
-DAEMON_ARGS="--daemon"
-
-[ -z "$AP_NAME" ]     || DAEMON_ARGS="$DAEMON_ARGS --name $AP_NAME"
-[ -z "$RUN_ONSTART" ]    || DAEMON_ARGS="$DAEMON_ARGS --on-start \"$RUN_ONSTART\""
-[ -z "$RUN_ONSTOP" ]     || DAEMON_ARGS="$DAEMON_ARGS --on-stop \"$RUN_ONSTOP\""
-[ -z "$OUTPUT" ]      || DAEMON_ARGS="$DAEMON_ARGS --output $OUTPUT"
-[ -z "$MDNS" ]        || DAEMON_ARGS="$DAEMON_ARGS --mdns $MDNS"
-[ -z "$PASSWORD" ]    || DAEMON_ARGS="$DAEMON_ARGS --password \"$PASSWORD\""
-[ -z "$OUTPUT_OPTS" ] || DAEMON_ARGS="$DAEMON_ARGS -- $OUTPUT_OPTS"
+SCRIPTNAME=/etc/init.d/$NAME
 
 # Exit if the package is not installed
-[ -x "$DAEMON" ] || { echo "$NAME is not installed" >&2 ; exit 1; }
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
@@ -46,51 +41,112 @@ DAEMON_ARGS="--daemon"
 # and status_of_proc is working.
 . /lib/lsb/init-functions
 
+#
+# Function that starts the daemon/service
+#
 do_start()
 {
-    start-stop-daemon --start --quiet \
-      --pidfile $PIDFILE \
-      --exec $DAEMON \
-      --nicelevel $NICE \
-      -- $DAEMON_ARGS
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+
+# This script is set to start running after all other services have started.
+# However, if you find that Shairport Sync is still being started before what it needs is ready,
+# uncomment the next line to get the script to wait for three seconds before attempting to start Shairport Sync.
+#	sleep 3
+
+# Uncomment just one of the following start-stop-daemon lines, or comment them all out and add your own.
+# In the default script, the first line is uncommented, selecting daemon mode (-d), the default device and software volume control
+# BTW, if you're using software volume control, you may have to use alsamixer or similar to set the output device's volume to its maximum level first
+# BTW2, you can use alsamixer to find device identifiers (e.g. hw:1) and mixer names (e.g. "Speaker"). No need to change ALSA's defaults.
+# BTW3, the argument after -a is simply the name the shairport service will be visible as.
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d || return 2
+#	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d -a "Topping TP30 or Griffin iMic on Raspberry Pi" -- -d hw:1 -t hardware -c "PCM" || return 2
+#	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d -a "'3D Sound' USB Soundcard on Raspberry Pi" -- -d hw:1 -t hardware -c "Speaker" || return 2
+# BTW, that "3D Sound" USB soundcard sometimes has the mixer name "Headphone" rather than "Speaker" -- use alsamixer to check.
+#	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d -a "IQaudIO" -- -d hw:1 -t hardware -c "Playback Digital" || return 2
+# BTW, newer versions of IQaudIO have a different mixer name -- use alsamixer to check.
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
 }
 
+#
+# Function that stops the daemon/service
+#
 do_stop()
 {
-    start-stop-daemon --stop --quiet \
-      --pidfile $PIDFILE \
-      --exec $DAEMON \
-      --name $NAME \
-      --retry=TERM/10/KILL/5
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
 }
 
-do_reload()
-{
-    start-stop-daemon --stop --signal 1 --quiet \
-      --pidfile $PIDFILE \
-      --name $NAME
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
 }
 
 case "$1" in
   start)
-	log_daemon_msg "Starting $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
 	do_start
-        log_end_msg $?
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
   stop)
-	log_daemon_msg "Stopping $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
 	do_stop
-        log_end_msg $?
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
-  reload)
-        log_daemon_msg "Reloading $DESC" "$NAME"
-        do_reload
-        log_end_msg $?
-        ;;
   status)
 	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
 	;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
   restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
 	log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
@@ -109,7 +165,8 @@ case "$1" in
 	esac
 	;;
   *)
-	echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
 	exit 3
 	;;
 esac
