Various improvements.

diff --git a/deb/openmediavault-usbbackup/usr/share/openmediavault/mkconf/usbbackup b/deb/openmediavault-usbbackup/usr/share/openmediavault/mkconf/usbbackup
--- a/deb/openmediavault-usbbackup/usr/share/openmediavault/mkconf/usbbackup
+++ b/deb/openmediavault-usbbackup/usr/share/openmediavault/mkconf/usbbackup
@@ -37,15 +37,16 @@ set -e
 . /etc/default/openmediavault
 . /usr/share/openmediavault/scripts/helper-functions
 
-OMV_USBBACKUP_UDEV_RULE_CONFIG=${OMV_USBBACKUP_UDEV_RULE_CONFIG:-"/etc/udev/rules.d/99-openmediavault-usbbackup.rules"}
 OMV_USBBACKUP_SCRIPTS_DIR=${OMV_USBBACKUP_SCRIPTS_DIR:-"/var/lib/openmediavault/usbbackup.d"}
 OMV_USBBACKUP_SCRIPTS_MASK=${OMV_USBBACKUP_SCRIPTS_MASK:-"755"}
+OMV_USBBACKUP_SCRIPTS_RSYNC_PREFIX=${OMV_USBBACKUP_SCRIPTS_RSYNC_PREFIX:-"rsync-"}
+OMV_USBBACKUP_SCRIPTS_JOBS_PREFIX=${OMV_USBBACKUP_SCRIPTS_JOBS_PREFIX:-"openmediavault-usbbackup-"}
 OMV_USBBACKUP_LOGFILE=${OMV_USBBACKUP_LOGFILE:-"/var/log/rsync.log"}
 
 # Create the backup jobs. Each job is configured in a seperate script.
 mkdir -p ${OMV_USBBACKUP_SCRIPTS_DIR}
-rm -f ${OMV_USBBACKUP_SCRIPTS_DIR}/rsync-*
-rm -f ${OMV_USBBACKUP_SCRIPTS_DIR}/sync-*
+find "${OMV_USBBACKUP_SCRIPTS_DIR}" -type f -iname "${OMV_USBBACKUP_SCRIPTS_RSYNC_PREFIX}*" -print0 | xargs -0r rm -f
+find "${OMV_USBBACKUP_SCRIPTS_DIR}" -type f -iname "${OMV_USBBACKUP_SCRIPTS_JOBS_PREFIX}*" -print0 | xargs -0r rm -f
 
 # Create the scripts regardless if enabled or disabled.
 xmlstarlet sel -t \
@@ -54,8 +55,9 @@ xmlstarlet sel -t \
   -b \
   ${OMV_CONFIG_FILE} | xmlstarlet unesc |
   while read uuid; do
-	  filename="${OMV_USBBACKUP_SCRIPTS_DIR}/rsync-${uuid}"
-	  runfile="/var/run/rsync-${uuid}"
+	  filename="${OMV_USBBACKUP_SCRIPTS_DIR}/${OMV_USBBACKUP_SCRIPTS_RSYNC_PREFIX}${uuid}"
+	  runfile="/var/run/${OMV_USBBACKUP_SCRIPTS_RSYNC_PREFIX}${uuid}"
+	  mountdir=$()
 
 	  xmlstarlet sel -t -m "//services/usbbackup/jobs/job[uuid='${uuid}']" \
 		-o "#!/bin/sh" -n \
@@ -68,19 +70,20 @@ xmlstarlet sel -t \
 		-o "  exit" -n \
 		-o "}" -n \
 		-o "[ -e ${runfile} ] && exit 1" -n \
-		-v "concat('if ! omv_is_mounted \"${OMV_MOUNT_DIR}/',fsuuid,'\" ; then')" -n \
-		-v "concat('    echo \"External storage device <${OMV_MOUNT_DIR}/',fsuuid,'> not mounted!\" | logger -s -t \$(basename \$0) 2>&1')" -n \
+		-v "concat('mountdir=\$(omv_get_devicefile_mount_dir \"',devicefile,'\")')" -n \
+		-o "if ! omv_is_mounted \"\${mountdir}\" ; then" -n \
+		-v "concat('    echo \"External storage device <',devicefile,'> not mounted!\" | logger -s -t \$(basename \$0) 2>&1')" -n \
 		-o "    exit 1" -n \
 		-o "fi" -n \
 		-o "trap cleanup 0 1 2 5 15" -n \
 		-o "touch ${runfile}" -n \
 		-i "mode = 'push' and usesubdir = '1'" \
 		  -o "# Create target directory on external storage device." -n \
-		  -v "concat('mkdir -p \"${OMV_MOUNT_DIR}/',fsuuid,'/')" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_NAME} -o "\"" -n \
-		  -v "concat('chmod 777 \"${OMV_MOUNT_DIR}/',fsuuid,'/')" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_NAME} -o "\"" -n \
+		  -o "mkdir -p \"\${mountdir}/" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_NAME} -o "\"" -n \
+		  -o "chmod 777 \"\${mountdir}/" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_NAME} -o "\"" -n \
 		-b \
 		-o "# Synchronise directories ..." -n \
-		-o "echo \"Please wait, syncing <" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_PATH} -v "concat('> to <${OMV_MOUNT_DIR}/',fsuuid)" -i "usesubdir = '1'" -o "/" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_NAME} -b -o "> ...\n\" | logger -s -t \$(basename \$0) 2>&1" -n \
+		-o "echo \"Please wait, syncing '" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_PATH} -o "' to '\${mountdir}" -i "usesubdir = '1'" -o "/" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_NAME} -b -o "' ...\n\" | logger -s -t \$(basename \$0) 2>&1" -n \
 		-o "rsync --verbose --log-file=\"${OMV_USBBACKUP_LOGFILE}\"" \
 		-i "recursive = '1'" -o " --recursive" -b \
 		-i "times = '1'" -o " --times" -b \
@@ -93,24 +96,28 @@ xmlstarlet sel -t \
 		-i "xattrs = '1'" -o " --xattrs" -b \
 		-i "partial = '1'" -o " --partial" -b \
 		-i "string-length(extraoptions) > 0" -v "concat(' ',extraoptions)" -b \
-		-i "mode = 'push'" -o " \"" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_PATH} -o "/\"" -v "concat(' \"${OMV_MOUNT_DIR}/',fsuuid)" -i "usesubdir = '1'" -o "/" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_NAME} -b -o "\"" -b \
-		-i "mode = 'pull'" -v "concat(' \"${OMV_MOUNT_DIR}/',fsuuid)" -i "usesubdir = '1'" -o "/" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_NAME} -b -o "/\" \"" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_PATH} -o "\"" -b \
+		-i "mode = 'push'" -o " \"" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_PATH} -o "/\" \"\${mountdir}" -i "usesubdir = '1'" -o "/" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_NAME} -b -o "\"" -b \
+		-i "mode = 'pull'" -o " \"\${mountdir}" -i "usesubdir = '1'" -o "/" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_NAME} -b -o "/\" \"" ${OMV_XMLSTARLET_GET_SHAREDFOLDER_PATH} -o "\"" -b \
 		-o " & wait \$!" \
 		${OMV_CONFIG_FILE} | xmlstarlet unesc > ${filename}
 	  chmod ${OMV_USBBACKUP_SCRIPTS_MASK} ${filename}
   done
 
-# Create the scripts executed by udev when the USB storage device is connected.
-# Process duplicate jobs per filesystem only once (emulate SQL 'DISTINCT' to
-# do this).
+# Create the scripts executed by systemd when the USB storage device is
+# connected. Process duplicate jobs per filesystem only once (emulate SQL
+# 'DISTINCT' to do this).
 xmlstarlet sel -t \
-  -m "//services/usbbackup/jobs/job[not(fsuuid=preceding-sibling::*/fsuuid)]" \
-    -v "fsuuid" -n \
+  -m "//services/usbbackup/jobs/job[not(devicefile=preceding-sibling::*/devicefile)]" \
+    -v "devicefile" -n \
   -b \
   ${OMV_CONFIG_FILE} | xmlstarlet unesc |
-  while read fsuuid; do
-	  filename="${OMV_USBBACKUP_SCRIPTS_DIR}/sync-${fsuuid}"
-	  runfile="/var/run/sync-${fsuuid}"
+  while read devicefile; do
+	  id=$(omv_md5 ${devicefile})
+	  scriptfile="${OMV_USBBACKUP_SCRIPTS_DIR}/${OMV_USBBACKUP_SCRIPTS_JOBS_PREFIX}${id}"
+	  runfile="/var/run/${OMV_USBBACKUP_SCRIPTS_JOBS_PREFIX}${id}"
+	  mountdir=$(omv_get_devicefile_mount_dir "${devicefile}")
+	  unitfile=$(systemd-escape --template=openmediavault-usbbackup@.service "${devicefile}")
+	  device=$(systemd-escape "${devicefile}")
 
 	  xmlstarlet sel -t \
 		-o "#!/bin/sh" -n \
@@ -123,63 +130,41 @@ xmlstarlet sel -t \
 		-o "  exit" -n \
 		-o "}" -n \
 		-o "[ -e ${runfile} ] && exit 1" -n \
-		-o "if [ ! -e \"/dev/disk/by-uuid/${fsuuid}\" ]; then" -n \
-		-o "    echo \"External storage device '/dev/disk/by-uuid/${fsuuid}' not found!\" | logger -s -t \$(basename \$0) 2>&1" -n \
+		-o "if [ ! -b \"${devicefile}\" ]; then" -n \
+		-o "    echo \"External storage device '${devicefile}' not found!\" | logger -s -t \$(basename \$0) 2>&1" -n \
 		-o "    omv_beep_error" -n \
 		-o "    exit 1" -n \
 		-o "fi" -n \
-		-o "if ! omv_is_mounted \"${OMV_MOUNT_DIR}/${fsuuid}\" ; then" -n \
-		-o "    echo \"External storage device '${OMV_MOUNT_DIR}/${fsuuid}' not mounted!\" | logger -s -t \$(basename \$0) 2>&1" -n \
+		-o "if ! omv_is_mounted \"${mountdir}\" ; then" -n \
+		-o "    echo \"External storage device '${devicefile}' not mounted!\" | logger -s -t \$(basename \$0) 2>&1" -n \
 		-o "    omv_beep_error" -n \
 		-o "    exit 1" -n \
 		-o "fi" -n \
 		-o "trap cleanup 0 1 2 5 15" -n \
 		-o "touch ${runfile}" -n \
 		-o "omv_beep_start" -n \
-		-m "//services/usbbackup/jobs/job[fsuuid='${fsuuid}' and enable='1']" \
-		  -v "concat('${OMV_USBBACKUP_SCRIPTS_DIR}/rsync-',uuid,' & wait \$!')" -n \
+		-m "//services/usbbackup/jobs/job[devicefile='${devicefile}' and enable='1']" \
+		  -v "concat('${OMV_USBBACKUP_SCRIPTS_DIR}/${OMV_USBBACKUP_SCRIPTS_RSYNC_PREFIX}',uuid,' & wait \$!')" -n \
 		-b \
 		-o "sync" -n \
-		-o "umount \"${OMV_MOUNT_DIR}/${fsuuid}\"" -n \
 		-o "omv_beep_ok" \
-		${OMV_CONFIG_FILE} | xmlstarlet unesc > ${filename}
-	  chmod ${OMV_USBBACKUP_SCRIPTS_MASK} ${filename}
+		${OMV_CONFIG_FILE} | xmlstarlet unesc > ${scriptfile}
+	  chmod ${OMV_USBBACKUP_SCRIPTS_MASK} ${scriptfile}
+
+	  cat <<EOF > ${unitfile}
+[Unit]
+Description=Execute the backup jobs when %I is plugged in
+BindsTo=${device}
+After=${device}
+
+[Service]
+Type=oneshot
+RemainAfterExit=true
+ExecStart=/bin/mount "${mountdir}"
+ExecStart=${scriptfile}
+ExecStop=/bin/umount "${mountdir}"
+
+[Install]
+WantedBy=multi-user.target
+EOF
   done
-
-# Create udev rules file.
-xmlstarlet sel -t \
-  -o "# Start at sdb to ignore the system hard drive" -n \
-  -o "KERNEL!=\"sd[b-z]*\", SUBSYSTEM!=\"block\", GOTO=\"openmediavault_usbbackup_end\"" -n \
-  -o "# Only process USB/eSATA devices" -n \
-  -o "ENV{ID_BUS}!=\"usb|ata\", GOTO=\"openmediavault_usbbackup_end\"" -n \
-  -o "# Skip all filesystems that does not match the given ID_FS_UUID" -n \
-  -m "//services/usbbackup/jobs/job[not(fsuuid=preceding-sibling::*/fsuuid)]" \
-	-i "count(../*[enable='1']) > 0" \
-	  -v "concat('ENV{ID_FS_UUID}==\"',fsuuid,'\", GOTO=\"openmediavault_usbbackup_automount\"')" -n \
-	-b \
-  -b \
-  -o "GOTO=\"openmediavault_usbbackup_end\"" -n \
-  -o "# Automount the filesystem." -n \
-  -o "LABEL=\"openmediavault_usbbackup_automount\"" -n \
-  -o "ACTION==\"add\", RUN+=\"/bin/systemctl start openmediavault-usbbackup-automountfs@%E{ID_FS_UUID}.service\"" -n \
-  -o "# Execute rsync command" -n \
-  -m "//services/usbbackup/jobs/job[not(fsuuid=preceding-sibling::*/fsuuid)]" \
-	-i "count(../*[enable='1']) > 0" \
-	  -v "concat('ACTION==\"add\", ENV{ID_FS_UUID}==\"',fsuuid,'\", RUN+=\"/usr/sbin/omv-run')" \
-	  -i "sendemail[. = '1']" \
-		-o " -e -s 'USB Backup (device=" -v fsuuid -o ")" \
-		-i "string-length(comment) > 0" \
-		  -v "concat(' - ',translate(comment,'\
-
-',' '))" \
-		-b \
-		-o "' -a 'From: USB Backup <root>'" \
-	  -b \
-	  -v "concat(' ${OMV_USBBACKUP_SCRIPTS_DIR}/sync-',fsuuid,'\"')" -n \
-	-b \
-  -b \
-  -o "# Cleanup after device removal" -n \
-  -o "ACTION==\"remove\", ENV{ID_FS_UUID}!=\"\", RUN+=\"/bin/systemctl stop openmediavault-usbbackup-automountfs@%E{ID_FS_UUID}.service\"" -n \
-  -o "# Exit" -n \
-  -o "LABEL=\"openmediavault_usbbackup_end\"" -n \
-  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_USBBACKUP_UDEV_RULE_CONFIG}
