Fix locking issue in SMB recycle bin cleanup and iptables scripts.
Signed-off-by: Volker Theile <votdev@gmx.de>

diff --git a/deb/openmediavault/usr/share/openmediavault/mkconf/iptables.d/10ifupdown b/deb/openmediavault/usr/share/openmediavault/mkconf/iptables.d/10ifupdown
--- a/deb/openmediavault/usr/share/openmediavault/mkconf/iptables.d/10ifupdown
+++ b/deb/openmediavault/usr/share/openmediavault/mkconf/iptables.d/10ifupdown
@@ -42,8 +42,9 @@ set -e
 # Make sure that only one instance of this shell script is running at
 # the same time.
 LOCK_FILE=/run/openmediavault-iptables.lock
-if ! mkdir "\${LOCK_FILE}" >/dev/null 2>&1; then
-	exit
+if ! mkdir "\${LOCK_FILE}"; then
+	echo "Locking failed, another job is running"
+	exit 0
 fi
 trap "rm -rf \${LOCK_FILE}" 0 1 2 3 5 15
 
diff --git a/deb/openmediavault/usr/share/openmediavault/mkconf/samba.d/40recyclebin b/deb/openmediavault/usr/share/openmediavault/mkconf/samba.d/40recyclebin
--- a/deb/openmediavault/usr/share/openmediavault/mkconf/samba.d/40recyclebin
+++ b/deb/openmediavault/usr/share/openmediavault/mkconf/samba.d/40recyclebin
@@ -47,7 +47,7 @@ xmlstarlet sel -t \
   ${OMV_CONFIG_FILE} | xmlstarlet unesc |
   while read uuid sharedfolderref recyclemaxage; do
 	  filename="${OMV_CRONSCRIPTS_DIR}/${OMV_SAMBA_SHARE_RECYCLE_CRONSCRIPT_PREFIX}${uuid}"
-	  lockfile="/run/${OMV_SAMBA_SHARE_RECYCLE_CRONSCRIPT_PREFIX}${uuid}"
+	  lockfile="/run/${OMV_SAMBA_SHARE_RECYCLE_CRONSCRIPT_PREFIX}${uuid}.lock"
 	  sfpath=$(omv_get_sharedfolder_path "${sharedfolderref}")
 	  recyclerepository="${sfpath}/${OMV_SAMBA_SHARE_RECYCLE_REPOSITORY}"
 	  amin=$((${recyclemaxage} * 24 * 60))
@@ -69,7 +69,8 @@ done
 # Exit if 'recyclemaxage' is zero.
 [ "\${amin}" -eq "0" ] && exit 0
 # Exit if another job is running.
-if ! mkdir "${lockfile}" &>/dev/null; then
+if ! mkdir "${lockfile}"; then
+	echo "Locking failed, another job is running"
 	exit 0
 fi
 # Initialize the trap to cleanup on exit.
