Use atomic mkdir to create lock file in SMB recycle dir cron script.
Signed-off-by: Volker Theile <votdev@gmx.de>

diff --git a/deb/openmediavault/usr/share/openmediavault/mkconf/samba.d/40recyclebin b/deb/openmediavault/usr/share/openmediavault/mkconf/samba.d/40recyclebin
--- a/deb/openmediavault/usr/share/openmediavault/mkconf/samba.d/40recyclebin
+++ b/deb/openmediavault/usr/share/openmediavault/mkconf/samba.d/40recyclebin
@@ -47,7 +47,7 @@ xmlstarlet sel -t \
   ${OMV_CONFIG_FILE} | xmlstarlet unesc |
   while read uuid sharedfolderref recyclemaxage; do
 	  filename="${OMV_CRONSCRIPTS_DIR}/${OMV_SAMBA_SHARE_RECYCLE_CRONSCRIPT_PREFIX}${uuid}"
-	  runfile="/var/run/${OMV_SAMBA_SHARE_RECYCLE_CRONSCRIPT_PREFIX}${uuid}"
+	  lockfile="/run/${OMV_SAMBA_SHARE_RECYCLE_CRONSCRIPT_PREFIX}${uuid}"
 	  sfpath=$(omv_get_sharedfolder_path "${sharedfolderref}")
 	  recyclerepository="${sfpath}/${OMV_SAMBA_SHARE_RECYCLE_REPOSITORY}"
 	  amin=$((${recyclemaxage} * 24 * 60))
@@ -69,11 +69,13 @@ done
 # Exit if 'recyclemaxage' is zero.
 [ "\${amin}" -eq "0" ] && exit 0
 # Exit if another job is running.
-[ -e ${runfile} ] && exit 0
+if ! mkdir "${lockfile}" &>/dev/null; then
+	exit 0
+fi
+# Initialize the trap to cleanup on exit.
+trap "rm -rf ${lockfile}; exit" 0 1 2 5 15
 # Exit if the recycle bin directory does not exist.
 [ ! -e "${recyclerepository}" ] && exit 0
-trap "rm -f ${runfile}; exit" 0 1 2 5 15
-touch ${runfile}
 echo "Please wait, empty recyle bin of <$sfpath> ..."
 find "${recyclerepository}" -mindepth 1 -amin +\${amin} -print0 | xargs -0r rm -rfv
 # Do a second run to remove empty directories.
